# Generated by Django 2.1.4 on 2019-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/profile_photos/default.jpg', upload_to='images/profile_photos'),
        ),
    ]
