# Generated by Django 2.1.4 on 2019-01-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190102_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cv_url',
            new_name='personal_url',
        ),
    ]
