# Generated by Django 3.2.7 on 2022-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orcid_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_gate_url',
            field=models.URLField(blank=True),
        ),
    ]
