# Generated by Django 2.1.4 on 2018-12-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Research',
            new_name='ResearchField',
        ),
    ]
