# Generated by Django 2.1.4 on 2018-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181215_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfield',
            name='image',
            field=models.ImageField(default='/Users/USER/Dropbox/Projectos/egichem/media/images/350x200.png', upload_to='images'),
        ),
    ]
