# Generated by Django 2.1.4 on 2018-12-16 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_researchfield_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('equipment', models.TextField()),
                ('image', models.ImageField(upload_to='images/lab')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
