# Generated by Django 2.1.4 on 2018-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_collaborator_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
