# Generated by Django 2.1.4 on 2018-12-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181216_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='scope',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
