# Generated by Django 2.1.4 on 2018-12-19 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181216_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('PostDoc Researcher', 'PostDoc Researcher'), ('PhD Student', 'PhD Student'), ('Research Fellows', 'Research Fellows'), ('MSc Students', 'MSc Students')], max_length=50)),
                ('research_area', models.CharField(blank=True, max_length=200)),
                ('thesis', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/people')),
                ('alumni', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
