# Generated by Django 2.1.4 on 2018-12-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20181219_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Professor', 'Professor'), ('PostDoc Researcher', 'PostDoc Researcher'), ('PhD Student', 'PhD Student'), ('Research Fellow', 'Research Fellow'), ('MSc Student', 'MSc Student'), ('Undergraduate Student', 'Undergraduate Student')], max_length=50),
        ),
    ]
