# Generated by Django 2.1.4 on 2019-01-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='images/profile_photos/default.jpg', upload_to='images/people'),
        ),
    ]
