# Generated by Django 2.1.4 on 2019-01-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190103_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_type', models.CharField(choices=[('article', 'Articles'), ('book-chapter', 'Book Chapter'), ('patent', 'Patent'), ('poster', 'Poster'), ('presentation', 'Presentation'), ('thesis', 'Thesis')], max_length=50)),
                ('authors', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=4)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('issue', models.CharField(blank=True, max_length=10)),
                ('pages', models.CharField(blank=True, max_length=20)),
                ('link', models.URLField(blank=True)),
                ('book_title', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('patent_number', models.CharField(blank=True, max_length=100)),
                ('conference', models.CharField(blank=True, max_length=200)),
                ('conference_city', models.CharField(blank=True, max_length=100)),
                ('conference_date', models.CharField(blank=True, max_length=100)),
                ('thesis_type', models.CharField(blank=True, choices=[('MSc', 'MSc Thesis'), ('PhD', 'PhD Thesis')], max_length=15)),
            ],
        ),
    ]
