# Generated by Django 2.1.4 on 2019-01-05 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
