# Generated by Django 2.1.4 on 2019-01-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_publication_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/publications'),
        ),
    ]
