# Generated by Django 2.1.4 on 2019-01-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_publication_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(default='images/publications/book_placeholder.jpg', upload_to='images/publications'),
        ),
    ]
