# Generated by Django 2.1.4 on 2019-01-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20190106_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='thesis_cooedinators',
            new_name='thesis_coordinators',
        ),
    ]
