# Generated by Django 2.1.4 on 2019-01-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190106_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='carlos-manuel-silva'),
            preserve_default=False,
        ),
    ]
