# Generated by Django 2.1.4 on 2019-01-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='images/profile_photos/default.jpg', upload_to='images/people'),
        ),
    ]
