# Generated by Django 2.1.4 on 2019-01-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20190107_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
