# Generated by Django 2.1.4 on 2019-01-15 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20190111_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('awarded_to', models.CharField(blank=True, max_length=500)),
                ('awarded_for', models.CharField(blank=True, max_length=500)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(default='images/awards/award-placeholder.png', upload_to='images/awards')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
