# Generated by Django 2.1.4 on 2019-01-16 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='tool',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
