# Generated by Django 2.1.5 on 2019-01-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20190116_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='collaborator',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='labunit',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='researchfield',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='labunit',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images/lab'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(default='images/350x200.png', upload_to='images/partners'),
        ),
        migrations.AlterField(
            model_name='researchfield',
            name='image',
            field=models.ImageField(default='images/350x200.png', upload_to='images/research-fields'),
        ),
    ]
