# Generated by Django 2.1.5 on 2019-01-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20190127_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
