# Generated by Django 2.2.4 on 2021-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_researchfield_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='labunit',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
