# Generated by Django 3.2 on 2021-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_labunit_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Researcher', 'Researcher'), ('PostDoc Researcher', 'PostDoc Researcher'), ('PhD Student', 'PhD Student'), ('Research Fellow', 'Research Fellow'), ('MSc Student', 'MSc Student'), ('Undergraduate Student', 'Undergraduate Student')], max_length=50),
        ),
    ]
