# Generated by Django 3.2.7 on 2021-12-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_mainresearchareas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainResearchAreas',
            new_name='MainResearchArea',
        ),
    ]
