# Generated by Django 5.1.1 on 2025-01-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_rename_mainresearchareas_mainresearcharea'),
    ]

    operations = [
        migrations.AddField(
            model_name='labunit',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/lab'),
        ),
        migrations.AddField(
            model_name='labunit',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/lab'),
        ),
        migrations.AddField(
            model_name='labunit',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/lab'),
        ),
    ]
