# Generated by Django 5.1.1 on 2025-01-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_labunit_image2_labunit_image3_labunit_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='visiting',
            field=models.BooleanField(default=False),
        ),
    ]
