# Generated by Django 2.1.4 on 2019-01-19 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cas', models.CharField(blank=True, max_length=500)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, max_length=500)),
                ('msds_link', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
