# Generated by Django 2.1.5 on 2019-01-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20190119_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='author',
            new_name='user',
        ),
    ]
