# Generated by Django 2.1.5 on 2019-01-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20190120_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
