# Generated by Django 2.1.5 on 2019-01-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20190120_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': (('manage_inventory', 'Can manage inventory'),)},
        ),
    ]
