# Generated by Django 2.1.5 on 2019-06-27 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'permissions': (('manage_inventory', 'Can manage inventory'),)},
        ),
        migrations.AlterField(
            model_name='material',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
