# Generated by Django 2.2.3 on 2019-07-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20190627_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='item_type',
            field=models.CharField(choices=[('Reagent', 'Reagent'), ('Materials', 'Materials'), ('Tools', 'Tools'), ('Others', 'Others')], default='Reagent', max_length=50),
        ),
    ]
