# Generated by Django 2.2.3 on 2019-07-27 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_material_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
