# Generated by Django 2.2.4 on 2021-03-10 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_auto_20190727_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('resource_type', models.TextField()),
                ('url1', models.URLField()),
                ('url2', models.URLField(blank=True)),
                ('url3', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.IntegerField(default=99)),
            ],
        ),
    ]
