# Generated by Django 2.2.4 on 2021-03-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_externalresources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalResources',
            new_name='ExternalResource',
        ),
    ]
