# Generated by Django 2.2.4 on 2021-03-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_auto_20210310_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalresource',
            name='url1_text',
            field=models.CharField(default='Link', max_length=15),
        ),
        migrations.AddField(
            model_name='externalresource',
            name='url2_text',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='externalresource',
            name='url3_text',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='resource_type',
            field=models.TextField(blank=True),
        ),
    ]
