# Generated by Django 2.2.4 on 2021-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20210310_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresource',
            name='url2_text',
            field=models.CharField(default='Link2', max_length=15),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='url3_text',
            field=models.CharField(default='Link3', max_length=15),
        ),
    ]
