# Generated by Django 3.2.7 on 2022-03-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_rename_mainresearchareas_mainresearcharea'),
        ('lab', '0016_auto_20210310_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('cleaning', models.ManyToManyField(blank=True, related_name='cleaning_team', to='website.Member')),
                ('safety', models.ManyToManyField(blank=True, related_name='safety_team', to='website.Member')),
                ('technic', models.ManyToManyField(blank=True, related_name='technic_team', to='website.Member')),
            ],
        ),
    ]
