# Generated by Django 3.2.7 on 2022-03-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_labteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labteam',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=3),
        ),
        migrations.AlterField(
            model_name='labteam',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
