# Generated by Django 3.2.7 on 2022-03-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_rename_mainresearchareas_mainresearcharea'),
        ('lab', '0018_auto_20220319_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=99)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='labteam',
            name='cleaning',
            field=models.ManyToManyField(blank=True, limit_choices_to={'alumni': False}, related_name='cleaning_team', to='website.Member'),
        ),
        migrations.AlterField(
            model_name='labteam',
            name='safety',
            field=models.ManyToManyField(blank=True, limit_choices_to={'alumni': False}, related_name='safety_team', to='website.Member'),
        ),
        migrations.AlterField(
            model_name='labteam',
            name='technic',
            field=models.ManyToManyField(blank=True, limit_choices_to={'alumni': False}, related_name='technic_team', to='website.Member'),
        ),
    ]
